### ISSUE TITLE
Mitigating network errors whilst accessing resources

### ISSUE THREAD

**Issue by lewismc** [Reading-eScience-Centre/covjson-reader#8]
Hi Folks,
I'm consistently having issues accessing covjson files hosted remotely. The covjson files are pretty large (375MB) so I know that this is the issue. An example file can be found at [coverage.covjson](http://home.apache.org/~lewismc/coverage.covjson), the error can be seen below.
The problem here is that the example file provided above is absolutely typical of the type of covjson I am working with. 
Any ideas how to address this issue? Is there a timeout trigger which I can increase to mitigate against the Network errors?
Thanks in advance.
<img width="833" alt="screen shot 2016-09-11 at 5 46 08 pm" src="https://cloud.githubusercontent.com/assets/1165719/18421756/8efcf618-7846-11e6-8ab5-44714266ea8e.png">

**Comment by lewismc** [comment]
The code I am using to access the covjson
```
<html>
<head>
	<style type="text/css">html, body, #map {
    width: 100%;
    height: 100%;
    }</style>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css">
	<link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet-coverage@0.6/leaflet-coverage.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>
	<script src="https://unpkg.com/covutils/covutils-lite.min.js"></script>
	<script src="https://unpkg.com/leaflet-coverage@0.6/leaflet-coverage.min.js"></script>
	<script src="https://cdn.jsdelivr.net/covjson-reader/0.16/covjson-reader.min.js"></script>
</head>
<body>
<div id="map">
<script type="text/javascript">
var map = L.map('map', { center: [10, 0], zoom: 2 })
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map)

var layers = L.control.layers(null, null, {collapsed: false}).addTo(map)

//var dataUrl = 'https://raw.githubusercontent.com/covjson/cookbook/master/examples/coverages/grid.covjson'
var dataUrl = 'http://home.apache.org/~lewismc/coverage.covjson'

var layer
CovJSON.read(dataUrl).then(function (coverage) {
  	layer = C.dataLayer(coverage, {keys: ['sea_ice_fraction']}).on('add', function () {
      	C.legend(layer).addTo(map)
      	map.fitBounds(layer.getBounds())
    }).addTo(map)
  	layers.addOverlay(layer, 'Sea Ice Fraction')
})

map.on('click', function (e) {
  	new C.DraggableValuePopup({
    	layers: [layer]
  	}).setLatLng(e.latlng).openOn(map)
})
</script>
</body>
</html>
```

**Comment by letmaik** [comment]
I'm not sure where that exact error comes from, could be a server issue even. But in general it's a bad idea to serve such massive CovJSON files if they are meant to be used in web apps. Some suggestions:

- Depending on your use case, downsample the grid or serve it in multiple resolutions, for example, have a different CovJSON file at different zoom levels. Note that we haven't devised a standard way for zoom levels yet (meaning leaflet-coverage doesn't support that out of the box), but have a look at https://github.com/covjson/specification/issues/29 for some discussion. 
- If your x and y axes are regularly spaced, use the short-hand notation instead of listing every coordinate.
- Try to follow https://covjson.org/cookbook/#encoding-advice as much as possible.

**Comment by jonblower** [comment]
and would compression help? This might help with the network errors, but of course the data will still expand on the client side.

**Comment by lewismc** [comment]
This issue will not be going away for a good while as I am working on a prototype for http://podaac.jpl.nasa.gov and we have TB of coverage data which I would very much like to visualize on our dataset landing pages using covjson.

These are some emerging issues which already seem to be pushing the possibly boundaries of browser-based vizualization for covjson... which is a good thing as it means we can improve the capabilities of the library based upon this use case.

@letmaik thanks for the hints.. I'll implement them all and see where I get.

@jonblower i also thought about this and I think that it is one of a number of contribution solutions. I did think about potentially suggesting CBOR as an alternative serialized data representation format. Does this have any merit? I've used it a few times before however I don't know a hellish lot about it.

**Comment by letmaik** [comment]
We did experiments with CBOR, and I am still desperately waiting for the [typed array extension of CBOR](https://tools.ietf.org/html/draft-jroatch-cbor-tags-04) to be finalised and implemented in client libraries. I think only then it would make sense to think about using CBOR, with a packed array representation (offset/factor plus special value for missing data), as this can then directly be read into a JavaScript typed array without any parsing overhead. But having said that, this would only push the boundary a little further and is not a magic solution for serving huge amounts of data in a single file/resource.

CovJSON itself can be used in many ways, and a direct translation of GeoTIFF/netCDF/... files to CovJSON in high resolution and serving that as-is to web clients in a single file is nearly always a bad idea, except when the spatial extent is small enough. Think about CovJSON more as an enabling tool in a REST API. For example, if your coverage is a grid and consists of several time steps, then it probably makes sense to use a tiled range representation and serve each time step separately so that browsers don't have to load the complete coverage if they just want to display/work with a single time step. And similarly with the zoom levels I mentioned.

Can you tell us a bit more about the kind of data you have? Is it all grids? Do you want to visualize the data on the landing pages in their full resolution? Do you also have vector data which would be suited for visualisation as an animation? (think https://www.windyty.com)

**Comment by lewismc** [comment]
The 2md paragraph above is very insightful. Thanks for that.
Now on to the questions
> Can you tell us a bit more about the kind of data you have? 

Yes. At the [PO.DAAC](http://podaac.jpl.nasa.gov/) we act as one of NASA's Data Active Archive Centers focused specifically on Physical Oceanographic data. Each dataset has a dataset landing page such as [GHRSST Level 4 ODYSSEA Mediterranean Sea Regional Foundation Sea Surface Temperature Analysis](http://podaac.jpl.nasa.gov/dataset/EUR-L4UHRfnd-MED-ODYSSEA). This includes a significant amount of insight into what the dataset is and how it can be accessed. I've intentionally highlighted a Level 4 dataset as it is gridded.

> Is it all grids? 

No, not all of it. We serve data from processing levels 2 - 4. A level 3 gridded dataset can be found at [SeaWinds on QuikSCAT Enhanced Resolution Regionally Gridded Sigma-0 (BYU, D. Long)](http://podaac.jpl.nasa.gov/dataset/QUIKSCAT_BYU_L3_OW_SIGMA0_ENHANCED), whereas some of the other datasets we have are level 2 (non-gridded) an example of which can be found at [SPURS-1 shipboard Acoustic Doppler Current Profiler data for N. Atlantic Endeavor and Knorr cruises](http://podaac.jpl.nasa.gov/dataset/SPURS1_ADCP). So the data we serve out of PO.DAAC really covers more or less every shape and size. Gridded and otherwise.

> Do you want to visualize the data on the landing pages in their full resolution? 

If possible yes. I think that this would be much much better than the current visualization which is a static map of sorts which is somewhat useless for the user. I was thinking that they could possibly select a spatial region for a specific temporal frequency and then be served the CovJSON... or something like that. This would mitigate against increased loading and rendering times for landing pages and would only be invoked if the user wished.

> Do you also have vector data which would be suited for visualisation as an animation?

At this point in time I think the majority of data is in netCDF however I can't confirm that. Maybe we could provide vector data. I would need to find this out.

**Comment by letmaik** [comment]
>     Do you also have vector data which would be suited for
>     visualisation as an animation?
>
> At this point in time I think the majority of data is in netCDF 
> however I can't confirm that. Maybe we could provide vector data. I 
> would need to find this out.
>
Just to respond to this quickly. By vector data I mean things like wind 
velocity (vector of speed and direction), not vector as in polygons etc. 
It's still gridded.

**Comment by lewismc** [comment]
Ah I see @letmaik sorry for late response. Yes we have wind vector data please see http://podaac.jpl.nasa.gov/dataset/CCMP_MEASURES_ATLAS_L4_OW_L3_0_WIND_VECTORS_FLK for an example. The data generation method produces a high-resolution (0.25 degree) gridded analysis data.

**Comment by lewismc** [comment]
Resolving as we are no longer using static files but instead accessing data through OPeNDAP Hyrax.
